name = "niepodzielni-ai-agent"
main = "src/index.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = false

[ai]
binding = "AI"

[[vectorize]]
binding = "VECTORIZE_PSY"
index_name = "psycholodzy"

[[vectorize]]
binding = "VECTORIZE_FAQ"
index_name = "faq"

[vars]
GATEWAY_BASE_URL = "https://gateway.ai.cloudflare.com/v1/f26ca3db380d36db86160d7f35e3968e/niepodzielni-ai-gateway/compat"
CHAT_MODEL       = "openai/gpt-4o-mini"
EMBED_MODEL      = "@cf/baai/bge-m3"
WP_API_URL       = "https://broken-specifications-contract-wealth.trycloudflare.com/wp-json/niepodzielni/v1"
